### ISSUE TITLE
Make error message more informative

### ISSUE THREAD

**Issue by Dimonza** [StackExchange/StackExchange.Precompilation#1]
When error happens in Error List there is only generic error message(**Error 2 An unhandled exception occured**) which does not explain problem behind that error. I encountered this issue when I had a view included in my project which was removed from disk/git. It took a lot of time to find issue because my project is big enough. Only that is show in Error List in VS.
https://github.com/StackExchange/StackExchange.Precompilation/blob/master/StackExchange.Precompilation.Build/Program.cs#L23
I use VS2012.
Thanks!

**Comment by m0sa** [comment]
you should now get one of the cs2001, cs2015 or cs1504 errors instead, [3.1.1 packages are on nuget](https://www.nuget.org/packages/StackExchange.Precompilation/3.1.1)
