### ISSUE TITLE
View lookup fails when website running as application in IIS

### ISSUE THREAD

**Issue by laughinggoose** [StackExchange/StackExchange.Precompilation#12]
I posted this question that has background information: https://stackoverflow.com/questions/42683111/how-can-i-fix-compilation-for-relative-paths-using-stackexchange-precompilation

[This line in PrecompiledViewEngine](https://github.com/StackExchange/StackExchange.Precompilation/blob/master/StackExchange.Precompilation/PrecompiledViewEngine.cs#L427) causes the path to be of the form `~/{app alias}/{controller}/{view}`. Changing the `VirtualPathUtility.ToAbsolute` to `VirtualPathUtility.ToAppRelative` fixed the issue for us.

**Comment by m0sa** [comment]
Thanks for reporting, I'll look into it
