### ISSUE TITLE
Using metaprogramming to minify HTML in compile-time

### ISSUE THREAD

**Issue by tompazourek** [StackExchange/StackExchange.Precompilation#17]
I was thinking about implementing a simple HTML minification of the compiled Razor views, just to experiment and play with compile-time transformations of views.

I'm thinking about starting with implementation of replacement of multiple spaces next to each other with a single space. I don't currently use `<textarea>` or `<pre>` tags in a way that it would cause an issue for them, multiple spaces in HTML attributes also don't have any significance in my project.

Would something like that be possible to achieve with the metaprogramming capabilities of StackExchange.Precompilation? Does this sound like a use case for that feature?

Is there any sample code, documentation, or projects doing something similar (metaprogramming stuff) with StackExchange.Precompilation? Any pointers, ideas, thoughts on how to start and where are appreciated.

Thanks.

**Comment by m0sa** [comment]
Are we talking about minimizing `.cshtml` views? In that case you either have to tweak the old MVC5 Razor engine, or work on it's output which would be possible with SE.Precompilation but extremely cumbersome, since you'd have to work on C# string literals passed into `Write` / `WriteLiteral` calls inside the generated view classes. [Enabling dynamic content compression in IIS](http://stackoverflow.com/q/702124/155005) is probably a better idea.

**Comment by tompazourek** [comment]
Thanks for the insights.

Yes, I mean minimizing `.cshtml` views. I have dynamic content compression enabled in IIS of course, but by my measurements, I can get still get up to 10% smaller responses by minifying the output HTML before the GZIP compression. And if that would be done in compile-time, it wouldn't increase server load.

I was thinking it would need to work with the strings in the generated view classes, as you mention, even when there's certain limitations to what's possible. As I said, I just want to start with getting rid of multiple spaces (tabs, newlines) next to each other, and experimenting with the effect this simple transformation can have.

**Comment by tompazourek** [comment]
I've failed to accomplish this through metaprogramming, but I managed to do a simple minification through tweaks in the Razor host factory.

If anybody's interested, I've open-sourced it here:
https://github.com/tompazourek/RazorHtmlMinifier.Mvc5
