### ISSUE TITLE
Compiler crashes when Reference has an Alias set

### ISSUE THREAD

**Issue by 0x53A** [StackExchange/StackExchange.Precompilation#2]
I have set a different Alias for a Reference:
![image](https://cloud.githubusercontent.com/assets/4236651/15162937/07a14b98-1706-11e6-8f83-2686dc947fff.png)

It crashes trying to parse it in ParseFileFromArg:
![image](https://cloud.githubusercontent.com/assets/4236651/15162979/34b1a31c-1706-11e6-9d61-8bc0a5fa87d8.png)

Edit:

I found 

```
                    // don't care about extern stuff for now..
                    // https://msdn.microsoft.com/en-us/library/ms173212.aspx
```

a few lines, above, so it seems you don't use aliases.

Would you accept a PR which adds support for this?

**Comment by m0sa** [comment]
@0x53A sure, PRs are welcome

**Comment by m0sa** [comment]
@0x53A can you create a PR for this, so I can merge it?

**Comment by 0x53A** [comment]
@m0sa PR sent. Thank you.
