### ISSUE TITLE
Failed to instantiate ICompileModule 'Namespace.SubNamespace.ClassName, Namespace.SubNamespace': Value cannot be null

### ISSUE THREAD

**Issue by itssimple** [StackExchange/StackExchange.Precompilation#22]
I have added `StackExchange.Precompilation.Build` to the target project, and `~.Metaprogramming` to the referenced project.

But I always end up with `Failed to instantiate ICompileModule 'x': Value cannot be null`.

This is the code I use in the module.

```csharp
using Microsoft.CodeAnalysis;
using StackExchange.Precompilation;

namespace Namespace.SubNamespace
{
	public class ClassName : ICompileModule
	{
		public void AfterCompile(AfterCompileContext context)
		{
		}

		public void BeforeCompile(BeforeCompileContext context)
		{
			context.Diagnostics.Add(
				Diagnostic.Create(
					new DiagnosticDescriptor("TEST", "TEST", "Hello meta programming world!", "TEST", DiagnosticSeverity.Info, true),
					Location.None));
		}
	}
}
```

And the build output has this info:
```plain
2>Task "Csc"
2>  C:\projectlocation\packages\StackExchange.Precompilation.Build.3.3.0\build\..\tools\StackExchange.Precompiler.exe 
  /noconfig 
  /nowarn:1701,1702,2008 
  /nostdlib+ 
  /platform:x86 
  /errorreport:prompt 
  /warn:4 
  /define:DEBUG;TRACE 
  /appconfig:Web.config 
  /errorendlocation 
  /preferreduilang:en-US 
  /highentropyva+ 
  [references] 
  /debug+ 
  /debug:full 
  /optimize- 
  /out:obj\Debug\project.dll 
  /ruleset:"MinimumRecommendedRules.ruleset" 
  /subsystemversion:6.00 
  [resources] 
  /target:library 
  /warnaserror- 
  /utf8output
  /analyzer:packages\..\Microsoft.CodeAnalysis.Analyzers.dll
  /analyzer:packages\..\Microsoft.CodeAnalysis.CSharp.Analyzers.dll
  [all files]
2>C:\projectlocation\Web.config(1,1): error SE001: Failed to instantiate ICompileModule 'Namespace.SubNamespace.ClassName, Namespace.SubNamespace': Value cannot be null.
2>  Parameter name: type
```

And finally, web.config

```xml
  <stackExchange.precompiler>
	<modules>
	  <add type="Namespace.SubNamespace.ClassName, Namespace.SubNamespace" />
	</modules>
  </stackExchange.precompiler>
```

**Comment by m0sa** [comment]
The module must be in a different project (.dll),, and referenced by the target project, so that it can be resolved when the compilation runs.

**Comment by itssimple** [comment]
I have a solution like this:

- Project (contains StackExchange.Precompilation.Build)
- ModuleProject (contains ICompileModule and StackExchange.Precompilation.Metaprogramming)

**Comment by m0sa** [comment]
Do you have a reference to ModuleProject in Project?

**Comment by itssimple** [comment]
Yes, the module is placed inside a project that is referenced as a "project reference".

And the build order is

1. ModuleProject
2. Target project

**Comment by m0sa** [comment]
[This](https://github.com/StackExchange/StackExchange.Precompilation/blob/releases/3.3.0/StackExchange.Precompilation.Build/Compilation.cs#L151) is the offending line (type is null), so the type specification is invalid.

Make sure `{{ModuleProject}}.dll` and `<add type="Namespace.SubNamespace.ClassName, {{ModuleProject}}" />` match.

If it still doesn't work, check the fusion log.

**Comment by itssimple** [comment]
You're a wizard!

I thought I was supposed to use the namespace in the module-file as "second" parameter.
So when I switched to just `Namespace`, it didn't complain any more.

**Comment by m0sa** [comment]
That's how types are usually specified in .config files. [See MSDN](https://msdn.microsoft.com/en-us/library/w3f99sx1(v=vs.110).aspx#Anchor_2) for more details. I'm glad I could help.
