### ISSUE TITLE
Doesn't build on Visual Studio 2017 and/or with custom Nuget repo path

### ISSUE THREAD

**Issue by scottstephens** [StackExchange/StackExchange.Precompilation#23]
It took me a bit of trial and  error to get things building with my setup. I think the two issues I had were running Visual Studio 2017 and using a non-default/custom Nuget repository path. 

The first problem I hit was a cryptic error message saying "IDE0006 Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled". The fix for this is to open the Nuget Package Manager Console and run `update-package -reinstall` (for more details see https://github.com/dotnet/roslyn/wiki/Diagnosing-Project-System-Build-Errors ).

The second problem was that there were many references to "../packages/..." in the project files. Many of these are updated automatically by Nuget, but not all of them. In the StackExchange.Precompilation.csproj, StackExchange.Precompilation.Build.csproj and StackExchange.Precompilation.Metaprogramming.csproj files, there were two groups of references that had to be modified: the Analyzer tags and the Error tags.

I've got a building version of the repo so you can check out the details: https://github.com/scottstephens/StackExchange.Precompilation

It's not directly pullable though, I wasn't sure how to get it working for other setups and mine simultaneously.

Thanks for the great work, it's a very cool project.

**Comment by m0sa** [comment]
Can you make a PR just for the sake of getting a diff?

**Comment by m0sa** [comment]
How do you set this non-default/custom repository path? Can't you just add it as a source instead?

**Comment by scottstephens** [comment]
It's the `repositoryPath` parameter in the `Nuget.config` file (see https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior).

It's different than sources; sources specify where to look for new packages; the repository path specifies where to store installed packages. I have a lot of solutions that use the same references, so I set one global directory for package installs rather than have duplicate files for each solution.

**Comment by m0sa** [comment]
Not sure that'll ever work correctly as long as the `HintPath` is added to the `.csproj`. In order to make it work properly we'd need a `<Project Sdk="Microsoft.NET.Sdk">` .csproj, but there's no way of testing the old MVC5 project types with that (which would still get the `HintPath`)

One workaround would be to setup the default `repositoryPath` (`.\packages`) to a `nuget.config` inside this project, to override your overrides. Would this be OK?

**Comment by scottstephens** [comment]
My patch to the project files solved all of my personal problems. My main goal with filing the issue was just to document what I figured out in case someone else hits the same issue in the future. If you don't want to change your build setup that's no problem for me.
