### ISSUE TITLE
Analysis task gets canceled

### ISSUE THREAD

**Issue by macote** [StackExchange/StackExchange.Precompilation#25]
In my moderately large MVC project, I get a "warning: analysis canceled" entry in my "Error List" window. I'm thinking that this [line](https://github.com/StackExchange/StackExchange.Precompilation/blob/3b564e56de52bcd1eb110c8f6313a48ad0039c8d/StackExchange.Precompilation.Build/Compilation.cs#L148) might be the reason why I see that. Can you please tell me what's the purpose of that line and if it can be moved or refactored?

Thanks.

**Comment by m0sa** [comment]
Good catch. IIRC this was the default behavior in the roslyn version I was looking how to run analyzers in the first place.

https://github.com/dotnet/roslyn/issues/11470
