### ISSUE TITLE
Unable to use C#7.0 features in .cs files

### ISSUE THREAD

**Issue by antur84** [StackExchange/StackExchange.Precompilation#30]
Hi

I'm trying to use any C#7.0 feature, like inline out params and digit_separator, in any *Controller.cs, but it won't compile as soon as I install Precompilation 3.3.0 package.

I don't get any error in the Error List, but you can see them in the output build log, that the precompilation compiler does not recognise the new features. If I force the /langlevel:7 flag it will complain that it has to be between 1-6

My easiest way of reproducing is starting a new project in VS (2017 community), MVC, based on net4.6.2.

* In HomeController, use some c#7 features, compile.
It won't compile.
* Update nuget packages (which will give you the latest codedom and compilers), compile again.
Success, all is good
* Install Precompilation package, compile
It won't compile anymore

Any ideas?

**Comment by m0sa** [comment]
SE Precompilation 3.* is built agains older roslyn packages that don't support c# 7 yet. Try the SE Precompilation pre-release packages (4.0) from the appveyor nuget feed described in the readme.

We're already running it in production on StackOverflow, I just didn't find time yet to do a release to nuget.org.
