### ISSUE TITLE
Have a 'quiet' mode

### ISSUE THREAD

**Issue by MatthewSteeples** [StackExchange/StackExchange.Precompilation#35]
I'm going to look at whether this is possible for me to implement as a Pull Request.

We suspect that this library is causing problems for a utility that we use because of the amount of output that this produces for our project.

I believe (though I'm still looking into it) that we'd basically just want to restrict the kinds of Diagnostic objects that are printed out to the console in the finally block of stackexchange.precompilation.build\compilation.cs line 209 (eg restrict it to errors only)

**Comment by m0sa** [comment]
Hidden diagnostics won't print to console in v4.5 anymore. All the other cases can be handled by suppression.
