### ISSUE TITLE
Please update Microsoft.AspNet.Mvc to 5.2.3

### ISSUE THREAD

**Issue by NickCraver** [StackExchange/StackExchange.Precompilation#36]
We're seeing a lot of reference mismatch errors due to Precompilation referencing Microsoft.AspNet.Mvc 5.0.0 in the latest VS and at the build prompt, but since ASP.NET is really stalled here (I doubt 5.2.4 will ever happen) I think it makes sense to just bump the reference up to 5.2.3 and get rid of these warnings for everyone. 

Thoughts?

**Comment by PatientNextZero** [comment]
Truthfully and Faithfulness

**Comment by PatientNextZero** [comment]
Aka GOUL
