### ISSUE TITLE
Cannot resolve partial views in different paths

### ISSUE THREAD

**Issue by tompazourek** [StackExchange/StackExchange.Precompilation#6]
I found out that the precompiled view engine cannot resolve partial views in different folders.

How to reproduce the issue:

1. Use `Test.WebApp` from the source code
2. Comment out fallback to `RoslynRazorViewEngine` in `Global.asax.cs`
3. Add partial view to `Views/OtherFolder/_PartialTest.cshtml` (you'll need to create `OtherFolder` directory inside `Views` first)
4. Inside `Views/Home/Index.cshtml` call `@Html.Partial("../OtherFolder/_PartialTest")`
5. Build in *Release* mode
6. Launch web app and **crash**

![capture](https://cloud.githubusercontent.com/assets/370699/15785321/ffb0001e-29b6-11e6-8b6d-4479ea9c64dd.PNG)

**Comment by m0sa** [comment]
Thanks for the report. Looking into it. The issue is with relative paths, `@Html.Partial("~/Views/OtherFolder/_PartialTest.cshtml")` work just fine.

**Comment by tompazourek** [comment]
Thanks for quick response!

I've had some problems with the absolute paths as well, but it might be some other issue. I will have to try it once again.

**Comment by tompazourek** [comment]
Thanks for a quick fix. I've checked and it seems alright now.

The problem I was having with absolute paths was the missing file extension in my path, so not really related to this.

**I would love to see this on NuGet whenever convenient.**
